[package]
name = "image-editor"
version = "0.1.1"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple image editor for ICI files"
license-file = "LICENSE"
repository = "https://github.com/raybritton/ici-image-editor"
readme = "README.md"
homepage = "https://github.com/raybritton/ici-image-editor"

[dependencies]
pixels-graphics-lib = "0.8.3"
color-eyre = "0.6.2"
log = "0.4.17"
directories = "4.0.1"
env_logger = "0.10.0"
ron = "0.8"
serde = { version = "1", features = ["derive"] }