[package]
name = "image-editor"
version = "0.3.0"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple image editor for ICI files"
license-file = "LICENSE"
repository = "https://github.com/raybritton/ici-image-editor"
readme = "README.md"
homepage = "https://github.com/raybritton/ici-image-editor"

[dependencies]
pixels-graphics-lib = "0.10.7"
color-eyre = "0.6.2"
log = "0.4.17"
directories = "5.0.0"
env_logger = "0.10.0"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
fnv = "1.0.3"
rfd = "0.11.3"