[package]
name = "image-editor"
version = "0.4.0"
edition = "2021"
authors = ["Emma Britton <emmabritton@pm.me>"]
description = "Simple image editor for ICI files"
license-file = "LICENSE"
repository = "https://github.com/emmabritton/ici-image-editor"
readme = "README.md"
homepage = "https://github.com/emmabritton/ici-image-editor"

[dependencies]
pixels-graphics-lib = "0.14.2"
color-eyre = "0.6.2"
log = "0.4.20"
directories = "5.0.1"
env_logger = "0.10.1"
ron = "0.8.1"
serde = { version = "1.0.193", features = ["derive"] }
fnv = "1.0.3"
rfd = "0.12.1"